//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_03_advanced_user_management_system.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdvanceUMSEntities : DbContext
    {
        public AdvanceUMSEntities()
            : base("name=AdvanceUMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account_type> Account_type { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<User_Role> User_Role { get; set; }
    }
}
